In [1]:
import pandas as pd 
import numpy as np

In [65]:
df = pd.read_csv('satgpa.csv')
df.insert(loc=0, column='ones', value=1) #Agregamos la columna de unos
df.drop(['sat_v', 'sat_m'], axis=1, inplace=True)
df.head()
# Dejamos solo las columnas de interés que son: sexo, total de percentil de SAT verbal y matemática, y el promedio GPA en highschool

ones  sex  sat_sum  hs_gpa  fy_gpa
0     1    1      127    3.40    3.18
1     1    2      122    4.00    3.33
2     1    2      116    3.75    3.25
3     1    1       95    3.75    2.42
4     1    1      107    4.00    2.63

In [66]:
y_column = df.pop('fy_gpa').to_numpy()
x_columns = df.to_numpy()

In [67]:
x_columns

array([[  1.  ,   1.  , 127.  ,   3.4 ],
       [  1.  ,   2.  , 122.  ,   4.  ],
       [  1.  ,   2.  , 116.  ,   3.75],
       ...,
       [  1.  ,   1.  , 114.  ,   3.5 ],
       [  1.  ,   1.  , 120.  ,   2.3 ],
       [  1.  ,   1.  ,  93.  ,   2.7 ]])

In [68]:
m, n = x_columns.shape

In [69]:
x_columns.shape

(1000, 4)

In [88]:
def linear_function_grades(X, y, theta):
    h = X @ theta
    return ((y - h) ** 2).sum() / (2 * len(X))

def linear_gradient_grades(X, y, theta):
    h = X @ theta
    return (X.T @ (h - y)) / len(X)

def gradient_descent_grades(X, y, theta_0, linear_function, linear_gradient, learning_rate=0.01, threshold= 0.001, max_iter=1000):
    theta = theta_0
    iteration = 0
    grades = []

    while np.linalg.norm(linear_gradient(X, y, theta)) > threshold and iteration < max_iter:
        iteration += 1
        theta = theta - (learning_rate * linear_gradient(X, y, theta))
        grades.append(linear_function(X, y, theta))
    return theta, grades

In [80]:
random_theta = np.random.rand(n,1)
random_theta

array([[0.30494045],
       [0.82025886],
       [0.88290934],
       [0.96776218]])

In [89]:
print(linear_function_grades(x_columns, y_column, random_theta))

4441821.499040509


In [90]:
print(linear_gradient_grades(x_columns, y_column, random_theta))

[[  92.66734391   92.51734391   92.59734391 ...   92.67734391
    93.90734391   93.46734391]
 [ 136.67745762  136.45485762  136.57357762 ...  136.69229762
   138.51761762  137.86465762]
 [9757.4882721  9741.9889221  9750.2552421  ... 9758.5215621
  9885.6162321  9840.1514721 ]
 [ 299.61481976  299.13510476  299.39095276 ...  299.64680076
   303.58046376  302.17329976]]


In [91]:
def gradient_descent_grades(X, y, theta_0, linear_function, linear_gradient, learning_rate=0.01, threshold= 0.001, max_iter=1000):
    theta = theta_0
    iteration = 0
    grades = []

    while np.linalg.norm(linear_gradient(X, y, theta)) > threshold and iteration < max_iter:
        iteration += 1
        theta = theta - (learning_rate * linear_gradient(X, y, theta))
        grades.append(linear_function(X, y, theta))
    return theta, grades
    
print(gradient_descent_grades(x_columns, y_column, random_theta, linear_function_grades, linear_gradient_grades))

(array([[-inf, -inf, -inf, ..., -inf, -inf, -inf],
       [-inf, -inf, -inf, ..., -inf, -inf, -inf],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]]), [51750517403.672325, 602964819680582.8, 7.025370831097003e+18, 8.185524876989356e+22, 9.537264170487812e+26, 1.111222667142214e+31, 1.2947274961636069e+35, 1.508535902739596e+39, 1.757652151975929e+43, 2.047906902139469e+47, 2.3860936733788444e+51, 2.7801278525847787e+55, 3.2392319559578697e+59, 3.77415148542298e+63, 4.397406431089728e+67, 5.123584306267486e+71, 5.969681573628194e+75, 6.955501453723028e+79, 8.104117426708882e+83, 9.44241327571461e+87, 1.1001712311762419e+92, 1.281851050748726e+96, 1.4935330698920885e+100, 1.740171784825058e+104, 2.027539866204653e+108, 2.3623632706252962e+112, 2.7524786641290825e+116, 3.2070168422828926e+120, 3.7366164398372963e+124, 4.353672931921176e+128, 5.0726287547373904e+132, 5.91031133614207e+136, 6.8863269478386785e+140, 8.023519597443642e+144, 